# -*- coding: utf-8 -*-
"""day4Assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bTXzT-OUoPQbljBPsjNZEKU3XwxEnSy

Assignment-4 Day-4
"""

#Assignment-4
#Day-5
#Date:02/07/2021
#Amal V.V
#amalvv2000cit@gmail.com

"""**Plane Landing**"""

Altitude=int(input("Enter the altitude of the Aeroplane  : " ))
if (Altitude<=1000):
    print("Exact altitude required for landing... Go for landing")
elif (1000 < Altitude <= 5000):
    print("Come down to 1000ft")
else:
    print("Go around and reattempt landing later")



